#!/bin/bash
while [[ $# > 1 ]]; do
key="$1"
case $key in
    -d)
    DELAY="$2"
    shift 
    ;;
    -n)
    NSNAPSHOTS="$2"
    shift
    ;;
    *)      
    # unknown option
    ;;
esac
shift
done
PID=$1
if [ -z "$PID" ]; then
    echo "usage: reap [-n <number of snapshots, defalut 10>] [-d <delay in secs, defalult 10>] <pid>"
    exit 1
fi 
kill -s 0 $PID &> /dev/null
if [ $? -ne 0 ]; then
    echo "Process with PID=${PID} does not exist"
    exit 1
fi
if [ -z "$JAVA_HOME" ]; then
    echo "System variable JAVA_HOME is not set"
    exit 1
fi 
FILE_SUFFIX=`date +%Y-%m-%d_%H-%M-%S`.txt 
top -d ${DELAY:-10} -b -n ${NSNAPSHOTS:-10} -H > top-${FILE_SUFFIX} &
for i in `seq 1 ${NSNAPSHOTS:-10}`; do $JAVA_HOME/bin/jstack $PID  >> dump-${FILE_SUFFIX}; sleep ${DELAY:-10}; done &
wait 